#!/bin/bash
# GMT script to plot CMPS computed from Fold python - binary cmpgmtup
#
#### Reading the parameters for this current project
#  line 1 = angle
#  line 2 =  BINX
#  line 3 = BINY
#  line 4 = MAXFOLD

declare -A gpar
index=0
while read line ; do
    gpar[$index]="$line"
    index=$(($index+1))
done < gplotpar
echo ${gpar[0]} 
angle="${gpar[0]}" 
echo $angle

awk  '{ if (NR>1) print $1, $2}' pol3.txt >pol3
awk  '{ if (NR>1) print $1, $2}' shots.txt >shots
awk  '{ if (NR>1) print $1, $2}' nodes.txt >nodes
output=foldhexbingmt.ps

grid="-B5000/5000WS"
dim="-JX5i"
regiao=`gmt gmtinfo pol3 -I1 `
echo $regiao

gmt gmtset COLOR_NAN gray
gmt makecpt -Crainbow -T0/${gpar[3]}/4 > fold.cpt
gmt xyz2grd -bi2 cmpgmtdown -I${gpar[1]}/${gpar[2]} -An -Gfold.nc $regiao
##gmt xyz2grd -bi4f cmp__.npz  -I100 -An -Gfold.nc $regiao

gmt grdimage fold.nc $regiao $dim $grid -Cfold.cpt -P -X2 -Y3. -K  >$output
gmt psxy $regiao $dim $grid -Sc.06 -Gblack -K -P nodes -O >> $output
gmt psxy $regiao $dim $grid -Sc.03 -Gblue -K -P shots -O >> $output

gmt psxy $regiao $dim $grid -W2,0.9  -K -P pol3 -O >> $output
gmt psscale -Dx1.2i/5.5i/5i/0.25ih -B100:HEXBIN-Pwave-fold-Mirror-field: -Cfold.cpt -O -K -P -X3 -Y2. >> $output

# rm foldgmt.nc
rm pol3
rm nodes
rm shots
rm fold.cpt
rm fold.nc
ps2pdf $output
okular foldhexbingmt.pdf&
rm $output




